### ISSUE TITLE
Compiling Issue: Cannot find module 'ng-vote'

### ISSUE THREAD

**Issue by Ejb503** [patrickvaler/ng-vote#1]
Thanks for contributing a useful plugin.
I have the plugin installed and working fine however it only recognises the module in my app when I point the code at ng-vote/dist, e.g.

import { NgVoteModule } from 'ng-vote/dist';

This works fine in development mode, however when I try to compile the code I get the following errors:

ng build --prod --aot
ERROR in //$$_gendir/node_modules/ng-vote/dist/ng-vote.ngfactory.ts (10,21): Cannot find module 'ng-vote'.
Module not found: Error: Can't resolve 'ng-vote' in /src/$$_gendir/app'

I suspect this has something to do with the module structure, however I don't have enough expertise in Angular to say for sure, do you have any idea how we can resolve this?

Thanks

**Comment by patrickvaler** [comment]
Hi

Thanks for reporting this issue.

There was an issue during publishing of the previous version. Please upgrade to ng-vote@0.1.5 and import the module like described in README:
`import { NgVoteModule } from 'ng-vote';`

The issue should be solved now. Please let me know if something does not work as expected.

Cheers,
Patrick

**Comment by ghost** [comment]
Not sure if related, but as above mine works perfectly in development, but fails when publishing
webpack output
```
WARNING in ./$$_gendir/node_modules/ng-vote/ng-vote.ngfactory.ts
      21:134-139 "export 'ɵa' (imported as 'i1') was not found in 'ng-vote'
      
      WARNING in ./$$_gendir/node_modules/ng-vote/ng-vote.ngfactory.ts
      58:32-37 "export 'ɵa' (imported as 'i1') was not found in 'ng-vote'
      
      WARNING in ./$$_gendir/node_modules/ng-vote/ng-vote.ngfactory.ts
      60:50-55 "export 'ɵa' (imported as 'i1') was not found in 'ng-vote'
```
Does it handle AOT?
